run:
  timeout: 20m

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/openmeterio/openmeter)
  goimports:
    local-prefixes: github.com/openmeterio/openmeter
  misspell:
    locale: US
  nolintlint:
    require-specific: true # require nolint directives to be specific about which linter is being skipped
  revive:
    confidence: 0
  sloglint:
    {}
    # kv-only: true # enforce using key-value pairs only
    # no-global: "all" # enforce not using global loggers
    # context: "scope" # enforce passing a context to loggers (if available)
    # key-naming-case: snake|camel # enforce a single key naming convention

linters:
  enable:
    - bodyclose
    - errcheck
    # - errorlint
    # - exhaustive
    - gci
    # - gochecknoinits
    # - goconst
    # - gocritic
    # - gocyclo
    # - godot
    - gofmt
    - gofumpt
    # - goheader
    - goimports
    # - gosec
    - gosimple
    - govet
    - ineffassign
    # - lll
    - misspell
    # - nlreturn
    - nolintlint
    # - revive
    - sloglint
    - staticcheck
    # - stylecheck
    - tenv
    # - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
    # - wsl

issues:
  exclude-dirs:
    - ci/internal
    - ci/dagger.gen.go
    - collector/benthos/internal
